
version: 2.1
orbs:
    node: circleci/node@4.1.0
jobs:
    test:
    docker:
        - image: cimg/node:12.20.0
    steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
        - run:
            command: react-scripts test
            name: Run YARN tests
workflows:
    node-tests:
    jobs:
        - test
        
        